#!/bin/bash

# Sets iTerm transparency

function transparency() { 

echo "Setting transparency to $1"

osascript -e "
tell application \"iTerm\"
    repeat with aWindow in windows
        tell aWindow
            tell current session
                set transparency to $1
            end tell
        end tell
    end repeat
end tell"

}
