# ╔═╗╔═╗╦ ╦╦═╗╔═╗
# ╔═╝╚═╗╠═╣╠╦╝║  
# ╚═╝╚═╝╩ ╩╩╚═╚═╝

# Oh My Zsh {{{

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
# ZSH_THEME="agnostergit"
ZSH_THEME="robbyrussell"

# Display username
#DEFAULT_USER=`whoami`

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in ~/.oh-my-zsh/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

#}}}
# Plugins {{{
#
# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.

plugins=(
  git 
  # osx # to control spotify
  # kubectl # For Kubernetes on Google Cloud
  # zsh-vi-mode
  zsh-autosuggestions
  zsh-syntax-highlighting
)

#}}}
# Options {{{

# Extended globbing options: allows ^(file.txt) to select everything but file.txt
# set -o gives full list of options
setopt extendedglob

# Avoid exit after Ctrl+d
set -o ignoreeof

# Neovim as Git default editor
export VISUAL='nvim'
export EDITOR="$VISUAL"

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

# FZF settings
# Defaults
export FZF_DEFAULT_OPTS='--height 40% --layout=reverse'
# Smart case: case insensitive only if all lowercase
#FZF DEFAULT
# Option 1 - Ripgrep only files in current directory 
# export FZF_DEFAULT_COMMAND='rg --files --no-ignore-vcs --hidden --smart-case'
# Option 2 - FD only files in current directory 
export FZF_DEFAULT_COMMAND='fd --type file --hidden --no-ignore --exclude .git'
# Option 3 - FD both files and directories: 
# export FZF_DEFAULT_COMMAND='fd . $HOME'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
#ESC+C
# Option 1 - Include hidden and ignored directories
# export FZF_ALT_C_COMMAND="fd --type directory --hidden --no-ignore --exclude .git . ~"
# Option 2 - Don't include hidden and ignored directories
export FZF_ALT_C_COMMAND="fd --type directory . $HOME"
export FZF_ALT_C_OPTS="--preview 'tree -C {} | head -200'"

# Default for vim**<tab>
_fzf_compgen_path() {
  fd --hidden --follow --exclude ".git" . "$1"
}
# Default for cd**<tab>
_fzf_compgen_dir() {
  fd --type d --hidden --follow --exclude ".git" . "$1"
}

#}}}
# Aliases {{{
#
# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh
alias skim='open -a skim'
alias vim='nvim'
# For Linux: when installing with linuxbrew
# alias vim = './home/linuxbrew/.linuxbrew/Cellar/neovim/0.4.3_1/bin/nvim'
alias vi='nvim -u NONE' # Load vim without settings
# Set neovim server name to use with neovim-remote (nvr)
# https://github.com/mhinz/neovim-remote)
export NVIM_LISTEN_ADDRESS=/tmp/nvimsocket
# alias jhubrun='/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --new-window --app=http://104.197.213.71'
# Call Python 3 by default. This does not and should not change the symlink to
# /usr/local/lib/python
# alias python='python3'
# alias pip='pip3'

alias chrome="/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome"

# Vifm mode: moves to current working directory after exiting
alias vifm='vicd'

alias mv='mv -i'

#}}}
# Path {{{

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/Users/fer/miniconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/fer/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/Users/fer/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/Users/fer/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

# TeX and X11 directories are added to path from /etc/paths.d

# Use latest version of Vim (symlinked to MacVim) instead of /usr/bin/vim
# This is not necessary since the following is already in PATH
# PATH="/usr/local/bin:$PATH"


# Add Latexmk to path
PATH="$PATH:/Library/TeX/texbin"

# Setting PATH for Python 2.7
# The original version is saved in .bash_profile.pysave
# PATH="$PATH:/Library/Frameworks/Python.framework/Versions/2.7/bin"

# Add Visual Studio Code (code)
PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"

# Dotfiles
# PATH="$PATH:/Users/Fer/.dotfiles/"

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/Fer/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/Fer/google-cloud-sdk/path.zsh.inc'; fi
# The next line enables shell command completion for gcloud.
if [ -f '/Users/Fer/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/Fer/google-cloud-sdk/completion.zsh.inc'; fi

# CS50 tutorial: add to path so it finds cs50.h
# export LIBRARY_PATH=/usr/local/lib
# Configure clang
# export CC="clang"
# export CFLAGS="-fsanitize=signed-integer-overflow -fsanitize=undefined -ggdb3 -O0 -std=c11 -Wall -Werror -Wextra -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable Wshadow"
# export LDLIBS="lcrypt -lcs50 -lm"
# export C_INCLUDE_PATH=/usr/local/include

# Vimgolf
# PATH="$PATH:/Users/Fer/.gem/ruby/2.3.0/bin"

# Rust and Cargo package manager: already added in ~/.zprofile
# PATH="$HOME/.cargo/bin:$PATH"

export PATH
typeset -gxU path # equivalent to 'export PATH' but also keep unique entries

# }}}
# Source files {{{

# Load oh-my-zsh: largest file, slow down startup
source $ZSH/oh-my-zsh.sh
source ~/.dotfiles/zsh/my_custom_commands.sh

# Initialize Pyenv: https://github.com/pyenv/pyenv#basic-github-checkout
eval "$(pyenv init -)"
#}}}
# Key Bindings {{{
bindkey -v # Vim mode for zsh command line
bindkey -M vicmd '^[[A' fzf-history-widget
bindkey -M viins '^[[A' fzf-history-widget

zle -N fancy-ctrl-z
# bindkey '^Z' fancy-ctrl-z
bindkey -M viins '^Z' fancy-ctrl-z
bindkey -M vicmd '^Z' fancy-ctrl-z
# }}}
# Other {{{

# Solves problem with Tmux and Conda environments
# [[ -z $TMUX ]] || source deactivate; #conda activate base


# Source FZF Autocompletion and Command Search
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# NVM: Node package manager
export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")" 
# [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"            # This loads nvm
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" --no-use # This loads nvm
# Option --no-use delays initialization of nvm so session loads faster
# As a result, nvm must be called every time I work on node: nvm use 13.9.0
#}}}
